FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*


RUN pip install --no-cache-dir \
    fastmcp \
    google-auth \
    google-auth-oauthlib \
    google-auth-httplib2 \
    google-api-python-client
    
COPY app/google_calendar_mcp_server.py /app/

EXPOSE 8090

CMD ["python","google_calendar_mcp_server.py"]